In [1]:
import pandas as pd

df = pd.read_csv("../data/ecommerce_orders_raw.csv")

df.head()

,Order_ID,Order_Date,Customer_ID,Product,Category,Region,Quantity,Unit_Price,Discount,Sales,Cost,Channel
0,ORD00001,2025-11-24,CUST1302,Keyboard,Accessories,North,2.0,1500,0.05,2850.0,1700,Website
1,ORD00002,2025/04/22,CUST1112,Laptop,Electronics,East,5.0,55000,0.05,261250.0,180000,Website
2,ORD00003,2025-03-23,CUST1047,Headphones,Accessories,East,3.0,2500,0.05,7125.0,4050,Marketplace
3,ORD00004,2025/11/06,CUST1040,Laptop,Electronics,EAST,6.0,55000,0.15,280500.0,216000,APP
4,ORD00005,05/07/2025,CUST1443,Monitor,Electronics,East,1.0,12000,0.05,11400.0,7600,website

In [2]:
df.shape

(5005, 12)

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5005 entries, 0 to 5004
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Order_ID     5005 non-null   str
 1   Order_Date   5005 non-null   str
 2   Customer_ID  5004 non-null   str
 3   Product      5005 non-null   str
 4   Category     5004 non-null   str
 5   Region       5004 non-null   str
 6   Quantity     5004 non-null   float64
 7   Unit_Price   5005 non-null   int64
 8   Discount     5004 non-null   str
 9   Sales        5004 non-null   float64
 10  Cost         5005 non-null   int64
 11  Channel      5005 non-null   str
dtypes: float64(2), int64(2), str(8)
memory usage: 469.3 KB

In [4]:
df.isnull().sum()

Order_ID       0
Order_Date     0
Customer_ID    1
Product        0
Category       1
Region         1
Quantity       1
Unit_Price     0
Discount       1
Sales          1
Cost           0
Channel        0
dtype: int64

In [5]:
df.duplicated().sum()

np.int64(5)

In [6]:
df["Category"].value_counts(dropna=False)

Category
Accessories    2501
Electronics    2384
electronics      60
accessories      59
NaN               1
Name: count, dtype: int64

In [7]:
df["Region"].value_counts(dropna=False)

Region
North     755
West      741
EAST      719
South     714
north     706
East      687
South     682
NaN         1
Name: count, dtype: int64

In [8]:
df["Channel"].value_counts(dropna=False)

Channel
website        1039
Marketplace    1032
APP            1004
App             969
Website         961
Name: count, dtype: int64

In [9]:
df["Order_Date"].head(20)

0     2025-11-24
1     2025/04/22
2     2025-03-23
3     2025/11/06
4     05/07/2025
5     2025-11-22
6     2025-03-25
7     2025/07/25
8     03/10/2025
9     2025/02/26
10    2025/12/15
11    14/09/2025
12    09-29-2025
13    13/02/2025
14    04-19-2025
15    2025-05-07
16    04/02/2025
17    08-31-2025
18    2025-12-11
19    2025-03-13
Name: Order_Date, dtype: str

In [10]:
df["Discount"].head(20)

0     0.05
1     0.05
2     0.05
3     0.15
4     0.05
5     0.05
6      0.2
7      0.1
8     0.15
9     0.15
10     10%
11     0.1
12      0%
13    0.05
14     0.1
15     0.2
16     0.2
17      5%
18    0.15
19    0.05
Name: Discount, dtype: str

In [11]:
df["Discount"].value_counts(dropna=False)

Discount
0.15    907
0.1     873
0       872
0.2     855
0.05    853
15%     134
10%     133
5%      129
20%     128
0%      120
NaN       1
Name: count, dtype: int64

In [12]:
df.describe()

          Quantity    Unit_Price          Sales           Cost
count  5004.000000   5005.000000    5004.000000    5005.000000
mean      3.444045  15346.213786   47641.045164   35681.736264
std       1.796199  17604.317952   66639.094428   49798.592531
min      -2.000000    800.000000 -104500.000000  -72000.000000
25%       2.000000   1500.000000    4560.000000    2700.000000
50%       4.000000   3200.000000   14400.000000    9500.000000
75%       5.000000  22000.000000   66300.000000   46500.000000
max       6.000000  55000.000000  330000.000000  216000.000000

In [13]:
df[df["Quantity"] <= 0][["Order_ID", "Quantity", "Sales"]]

      Order_ID  Quantity    Sales
54    ORD00055      -2.0  -4000.0
135   ORD00136      -1.0 -23800.0
369   ORD00370      -1.0 -25200.0
382   ORD00383      -1.0  -2125.0
392   ORD00393      -1.0 -44000.0
...        ...       ...      ...
4634  ORD04635      -1.0 -18700.0
4669  ORD04670      -2.0  -5760.0
4786  ORD04787      -2.0 -22800.0
4930  ORD04931      -1.0  -9600.0
4969  ORD04970      -2.0 -53200.0

[71 rows x 3 columns]

In [14]:
df["Quantity"].value_counts().sort_index()

Quantity
-2.0     32
-1.0     39
 1.0    823
 2.0    801
 3.0    798
 4.0    876
 5.0    796
 6.0    839
Name: count, dtype: int64

In [15]:
df["Quantity"].value_counts().sort_index()

Quantity
-2.0     32
-1.0     39
 1.0    823
 2.0    801
 3.0    798
 4.0    876
 5.0    796
 6.0    839
Name: count, dtype: int64

In [16]:
df[["Quantity", "Unit_Price", "Discount", "Sales"]].head(10)

   Quantity  Unit_Price Discount     Sales
0       2.0        1500     0.05    2850.0
1       5.0       55000     0.05  261250.0
2       3.0        2500     0.05    7125.0
3       6.0       55000     0.15  280500.0
4       1.0       12000     0.05   11400.0
5       3.0        2500     0.05    7125.0
6       6.0        1500      0.2    7200.0
7       5.0         800      0.1    3600.0
8       5.0        3200     0.15   13600.0
9       6.0       28000     0.15  142800.0

In [17]:
print("DATA QUALITY SUMMARY")
print("--------------------")

print("Rows:", len(df))
print("Columns:", len(df.columns))

print("\nMissing values:")
print(df.isnull().sum())

print("\nDuplicate rows:", df.duplicated().sum())

print("Duplicate Order IDs:", df["Order_ID"].duplicated().sum())

print("Non-positive quantities:", (df["Quantity"] <= 0).sum())

print("\nCategory values:")
print(df["Category"].value_counts(dropna=False))

print("\nRegion values:")
print(df["Region"].value_counts(dropna=False))

print("\nChannel values:")
print(df["Channel"].value_counts(dropna=False))

print("\nDiscount values:")
print(df["Discount"].value_counts(dropna=False))

DATA QUALITY SUMMARY
--------------------
Rows: 5005
Columns: 12

Missing values:
Order_ID       0
Order_Date     0
Customer_ID    1
Product        0
Category       1
Region         1
Quantity       1
Unit_Price     0
Discount       1
Sales          1
Cost           0
Channel        0
dtype: int64

Duplicate rows: 5
Duplicate Order IDs: 5
Non-positive quantities: 71

Category values:
Category
Accessories    2501
Electronics    2384
electronics      60
accessories      59
NaN               1
Name: count, dtype: int64

Region values:
Region
North     755
West      741
EAST      719
South     714
north     706
East      687
South     682
NaN         1
Name: count, dtype: int64

Channel values:
Channel
website        1039
Marketplace    1032
APP            1004
App             969
Website         961
Name: count, dtype: int64

Discount values:
Discount
0.15    907
0.1     873
0       872
0.2     855
0.05    853
15%     134
10%     133
5%      129
20%     128
0%      120
NaN       1
Name: count, dtype: int64

In [18]:
df[df.isnull().any(axis=1)]

,Order_ID,Order_Date,Customer_ID,Product,Category,Region,Quantity,Unit_Price,Discount,Sales,Cost,Channel
87,ORD00088,2025/06/26,CUST1436,Webcam,Accessories,NaN,6.0,3200,0.1,17280.0,11400,website
431,ORD00432,01-18-2025,NaN,Monitor,Electronics,South,5.0,12000,0.05,57000.0,38000,Website
811,ORD00812,29/11/2025,CUST1274,Tablet,NaN,South,1.0,22000,0.1,19800.0,15500,Marketplace
1222,ORD01223,23/06/2025,CUST1083,Keyboard,Accessories,north,3.0,1500,0,NaN,2550,APP
2444,ORD02445,2025/01/30,CUST1169,Keyboard,Accessories,north,6.0,1500,NaN,9000.0,5100,Website
3555,ORD03556,2025/02/04,CUST1385,Smartphone,Electronics,West,NaN,28000,10%,151200.0,123000,Marketplace

In [19]:
df[df["Customer_ID"].isna()]

,Order_ID,Order_Date,Customer_ID,Product,Category,Region,Quantity,Unit_Price,Discount,Sales,Cost,Channel
431,ORD00432,01-18-2025,NaN,Monitor,Electronics,South,5.0,12000,0.05,57000.0,38000,Website

In [20]:
df_clean = df.copy()

In [21]:
df_clean["Customer_ID"] = df_clean["Customer_ID"].fillna("UNKNOWN")

In [22]:
df_clean[df_clean["Category"].isna()][["Order_ID", "Product", "Category"]]

     Order_ID Product Category
811  ORD00812  Tablet      NaN

In [23]:
df[df["Product"] == "Tablet"][["Product", "Category"]].value_counts(dropna=False)

Product  Category
Tablet   Electronics    586
         electronics     17
         NaN              1
Name: count, dtype: int64

In [24]:
df_clean.loc[df_clean["Product"] == "Tablet", "Category"] = (
    df_clean.loc[df_clean["Product"] == "Tablet", "Category"].fillna("Electronics")
)

In [25]:
df_clean[df_clean["Region"].isna()][["Order_ID", "Product", "Region"]]

    Order_ID Product Region
87  ORD00088  Webcam    NaN

In [26]:
df[df["Product"] == "Webcam"][["Product", "Region"]].value_counts(dropna=False)

Product  Region
Webcam   North     116
         West      102
         South      96
         East       92
         South      91
         EAST       90
         north      83
         NaN         1
Name: count, dtype: int64

In [27]:
df_clean["Region"] = df_clean["Region"].fillna("UNKNOWN")

In [28]:
df_clean["Region"] = df_clean["Region"].str.strip().str.title()

In [29]:
df_clean["Category"] = df_clean["Category"].str.strip().str.title()

In [30]:
df_clean["Channel"] = df_clean["Channel"].str.strip().str.title()

In [31]:
df_clean["Discount"] = (
    df_clean["Discount"]
    .astype("string")
    .str.strip()
    .str.replace("%", "", regex=False)
    .astype(float) / 100
)

In [32]:
discount_from_sales = (
    1 - df_clean["Sales"] /
    (df_clean["Quantity"] * df_clean["Unit_Price"])
)

df_clean["Discount"] = df_clean["Discount"].fillna(discount_from_sales)

In [33]:
quantity_from_sales = (
    df_clean["Sales"] /
    (df_clean["Unit_Price"] * (1 - df_clean["Discount"]))
)

df_clean["Quantity"] = df_clean["Quantity"].fillna(quantity_from_sales)

In [34]:
sales_from_formula = (
    df_clean["Quantity"] *
    df_clean["Unit_Price"] *
    (1 - df_clean["Discount"])
)

df_clean["Sales"] = df_clean["Sales"].fillna(sales_from_formula)

In [35]:
df_clean["Order_Date"] = pd.to_datetime(
    df_clean["Order_Date"],
    format="mixed",
    errors="coerce"
)

In [36]:
df_clean["Quantity"] = df_clean["Quantity"].round().astype("Int64")

In [37]:
df_clean = df_clean.drop_duplicates().copy()

In [38]:
df_clean["Order_Type"] = df_clean["Quantity"].apply(
    lambda x: "Return" if x < 0 else "Sale"
)

In [39]:
df_clean["Profit"] = df_clean["Sales"] - df_clean["Cost"]

In [40]:
df_clean.to_csv(
    "../data/ecommerce_orders_clean.csv",
    index=False
)

In [41]:
sales_from_formula = (
    df_clean["Quantity"]
    * df_clean["Unit_Price"]
    * (1 - df_clean["Discount"])
)

df_clean["Sales"] = df_clean["Sales"].fillna(sales_from_formula)

In [42]:
df_clean["Order_Date"] = pd.to_datetime(
    df_clean["Order_Date"],
    format="mixed",
    errors="coerce"
)

In [43]:
df_clean["Quantity"] = df_clean["Quantity"].round().astype("Int64")

In [44]:
df_clean = df_clean.drop_duplicates().copy()

In [45]:
df_clean["Order_Type"] = df_clean["Quantity"].apply(
    lambda x: "Return" if x < 0 else "Sale"
)

In [46]:
import numpy as np

df_clean["Profit"] = np.where(
    df_clean["Quantity"] < 0,
    df_clean["Sales"] + df_clean["Cost"].abs(),
    df_clean["Sales"] - df_clean["Cost"].abs()
)

In [47]:
df_clean["Profit_Margin"] = np.where(
    df_clean["Sales"] != 0,
    df_clean["Profit"] / df_clean["Sales"].abs(),
    np.nan
)

In [48]:
df_clean.to_csv(
    "../data/ecommerce_orders_clean.csv",
    index=False
)

In [49]:
df_clean.isnull().sum()

Order_ID         0
Order_Date       0
Customer_ID      0
Product          0
Category         0
Region           0
Quantity         0
Unit_Price       0
Discount         0
Sales            0
Cost             0
Channel          0
Order_Type       0
Profit           0
Profit_Margin    0
dtype: int64

In [50]:
df_clean.duplicated().sum()

np.int64(0)

In [51]:
df_clean["Order_Date"].dtype

dtype('<M8[us]')

In [52]:
df_clean["Discount"].dtype

dtype('float64')

In [53]:
df_clean["Order_Type"].value_counts()

Order_Type
Sale      4929
Return      71
Name: count, dtype: int64

In [54]:
df_clean.shape

(5000, 15)

In [55]:
print("FINAL CLEANING CHECK")
print("--------------------")

print("Rows:", len(df_clean))
print("Columns:", len(df_clean.columns))

print("\nMissing values:")
print(df_clean.isnull().sum())

print("\nDuplicate rows:", df_clean.duplicated().sum())

print("\nData types:")
print(df_clean.dtypes)

FINAL CLEANING CHECK
--------------------
Rows: 5000
Columns: 15

Missing values:
Order_ID         0
Order_Date       0
Customer_ID      0
Product          0
Category         0
Region           0
Quantity         0
Unit_Price       0
Discount         0
Sales            0
Cost             0
Channel          0
Order_Type       0
Profit           0
Profit_Margin    0
dtype: int64

Duplicate rows: 0

Data types:
Order_ID                    str
Order_Date       datetime64[us]
Customer_ID                 str
Product                     str
Category                    str
Region                      str
Quantity                  Int64
Unit_Price                int64
Discount                float64
Sales                   float64
Cost                      int64
Channel                     str
Order_Type                  str
Profit                  float64
Profit_Margin           float64
dtype: object

In [56]:
df_clean["Order_Type"].value_counts()

Order_Type
Sale      4929
Return      71
Name: count, dtype: int64

In [57]:
sales_only = df_clean[df_clean["Order_Type"] == "Sale"]

sales_only["Sales"].sum()

np.float64(239203240.0)

In [58]:
sales_only["Profit"].sum()

np.float64(60014280.0)

In [59]:
sales_only["Sales"].mean()

np.float64(48529.77074457294)

In [60]:
sales_only["Profit"].mean()

np.float64(12175.751673767498)

In [61]:
sales_only.groupby("Product")["Sales"].sum().sort_values(ascending=False)

Product
Laptop        105039000.0
Smartphone     54580400.0
Tablet         41169700.0
Monitor        22534800.0
Webcam          6580480.0
Headphones      4578125.0
Keyboard        3102375.0
Mouse           1618360.0
Name: Sales, dtype: float64

In [62]:
sales_only.groupby("Product")["Profit"].sum().sort_values(ascending=False)

Product
Laptop        28395000.0
Smartphone    10177400.0
Tablet         8898700.0
Monitor        6643200.0
Webcam         2244680.0
Headphones     1829525.0
Keyboard       1147375.0
Mouse           678400.0
Name: Profit, dtype: float64

In [63]:
sales_only.groupby("Category")["Sales"].sum().sort_values(ascending=False)

Category
Electronics    223323900.0
Accessories     15879340.0
Name: Sales, dtype: float64

In [64]:
sales_only.groupby("Category")["Profit"].sum().sort_values(ascending=False)

Category
Electronics    54114300.0
Accessories     5899980.0
Name: Profit, dtype: float64

In [65]:
sales_only.groupby("Region")["Sales"].sum().sort_values(ascending=False)

Region
East       68854910.0
South      68312090.0
North      66476030.0
West       35542930.0
Unknown       17280.0
Name: Sales, dtype: float64

In [66]:
sales_only["Customer_ID"].nunique()

451

In [67]:
sales_only.groupby("Customer_ID")["Sales"].sum().sort_values(ascending=False).head(10)

Customer_ID
CUST1289    1554055.0
CUST1163    1511660.0
CUST1347    1494030.0
CUST1214    1469280.0
CUST1387    1464695.0
CUST1359    1259225.0
CUST1223    1212785.0
CUST1350    1212225.0
CUST1404    1170130.0
CUST1217    1160900.0
Name: Sales, dtype: float64

In [68]:
sales_only.groupby("Customer_ID")["Profit"].sum().sort_values(ascending=False).head(10)

Customer_ID
CUST1289    465565.0
CUST1163    414850.0
CUST1347    393830.0
CUST1387    359305.0
CUST1223    344875.0
CUST1005    337510.0
CUST1217    334750.0
CUST1214    332240.0
CUST1411    298095.0
CUST1172    292640.0
Name: Profit, dtype: float64

In [69]:
sales_only.groupby("Discount")["Sales"].sum().sort_values(ascending=False)

Discount
0.0000    51146200.0
0.0005    43261195.0
0.0010    42181470.0
0.0015    38722005.0
0.0020    38187920.0
0.1000     7362720.0
0.1500     7012925.0
0.0500     5894085.0
0.2000     5434720.0
Name: Sales, dtype: float64

In [70]:
sales_only.groupby("Discount")["Profit"].sum().sort_values(ascending=False)

Discount
0.0000    16803300.0
0.0005    12616665.0
0.0010    10579160.0
0.0015     8006275.0
0.0020     6195210.0
0.1000     1825840.0
0.0500     1672195.0
0.1500     1432975.0
0.2000      882660.0
Name: Profit, dtype: float64

In [71]:
sales_only.groupby(
    sales_only["Order_Date"].dt.to_period("M")
)["Sales"].sum()

Order_Date
2025-01    19945115.0
2025-02    17991185.0
2025-03    20305760.0
2025-04    19455330.0
2025-05    19724785.0
2025-06    15414915.0
2025-07    21614310.0
2025-08    20790385.0
2025-09    19965135.0
2025-10    19787265.0
2025-11    21831380.0
2025-12    22377675.0
Freq: M, Name: Sales, dtype: float64

In [72]:
sales_only.groupby(
    sales_only["Order_Date"].dt.to_period("M")
)["Profit"].sum()

Order_Date
2025-01    4985515.0
2025-02    4530945.0
2025-03    5181380.0
2025-04    5071250.0
2025-05    5101355.0
2025-06    3766425.0
2025-07    5296200.0
2025-08    4995275.0
2025-09    5110865.0
2025-10    5022185.0
2025-11    5543790.0
2025-12    5409095.0
Freq: M, Name: Profit, dtype: float64

In [73]:
sales_only.groupby("Channel")["Sales"].sum().sort_values(ascending=False)

Channel
App            97171515.0
Website        94844990.0
Marketplace    47186735.0
Name: Sales, dtype: float64

In [74]:
sales_only.groupby("Channel")["Profit"].sum().sort_values(ascending=False)

Channel
App            24491425.0
Website        23805790.0
Marketplace    11717065.0
Name: Profit, dtype: float64

In [75]:
returns = df_clean[df_clean["Order_Type"] == "Return"]

print("Return Orders:", len(returns))
print("Return Quantity:", returns["Quantity"].sum())
print("Return Sales Impact:", returns["Sales"].sum())
print("Return Profit Impact:", returns["Profit"].sum())

Return Orders: 71
Return Quantity: -103
Return Sales Impact: -1231190.0
Return Profit Impact: -297300.0

In [76]:
total_sales = sales_only["Sales"].sum()
total_sales

np.float64(239203240.0)

In [77]:
total_profit = sales_only["Profit"].sum()
total_profit

np.float64(60014280.0)

In [78]:
net_sales = df_clean["Sales"].sum()
net_sales

np.float64(237972050.0)

In [79]:
net_profit = df_clean["Profit"].sum()
net_profit

np.float64(59716980.0)

In [80]:
return_rate = len(returns) / len(df_clean) * 100
return_rate

1.4200000000000002

In [81]:
return_quantity_rate = (
    abs(returns["Quantity"].sum()) /
    sales_only["Quantity"].sum()
) * 100

return_quantity_rate

np.float64(0.5945509120295543)

In [82]:
returns.groupby("Product")["Quantity"].sum().abs().sort_values(ascending=False)

Product
Smartphone    18
Mouse         17
Webcam        17
Headphones    13
Tablet        13
Monitor       11
Keyboard       8
Laptop         6
Name: Quantity, dtype: Int64

In [83]:
returns.groupby("Product")["Sales"].sum().sort_values()

Product
Smartphone   -457800.0
Laptop       -297000.0
Tablet       -248600.0
Monitor      -127200.0
Webcam        -48320.0
Headphones    -28750.0
Mouse         -12120.0
Keyboard      -11400.0
Name: Sales, dtype: float64

In [84]:
df_clean["Sales"].sum()

np.float64(237972050.0)

In [85]:
df_clean["Profit"].sum()

np.float64(59716980.0)

In [86]:
df_clean["Profit"].sum() / df_clean["Sales"].abs().sum()

np.float64(0.24837116714107876)

In [87]:
sales_only.groupby("Discount")["Sales"].agg(
    ["count", "sum", "mean"]
).sort_index()

          count         sum          mean
Discount
0.0000      978  51146200.0  52296.728016
0.0005      842  43261195.0  51379.091449
0.0010      854  42181470.0  49392.822014
0.0015      895  38722005.0  43264.810056
0.0020      846  38187920.0  45139.385343
0.0500      126   5894085.0  46778.452381
0.1000      130   7362720.0  56636.307692
0.1500      133   7012925.0  52728.759398
0.2000      125   5434720.0  43477.760000

In [88]:
sales_only.groupby("Discount")["Profit"].agg(
    ["count", "sum", "mean"]
).sort_index()

          count         sum          mean
Discount
0.0000      978  16803300.0  17181.288344
0.0005      842  12616665.0  14984.162708
0.0010      854  10579160.0  12387.775176
0.0015      895   8006275.0   8945.558659
0.0020      846   6195210.0   7322.943262
0.0500      126   1672195.0  13271.388889
0.1000      130   1825840.0  14044.923077
0.1500      133   1432975.0  10774.248120
0.2000      125    882660.0   7061.280000

In [89]:
monthly_performance = sales_only.groupby(
    sales_only["Order_Date"].dt.to_period("M")
).agg(
    Sales=("Sales", "sum"),
    Profit=("Profit", "sum")
)

monthly_performance

                 Sales     Profit
Order_Date
2025-01     19945115.0  4985515.0
2025-02     17991185.0  4530945.0
2025-03     20305760.0  5181380.0
2025-04     19455330.0  5071250.0
2025-05     19724785.0  5101355.0
2025-06     15414915.0  3766425.0
2025-07     21614310.0  5296200.0
2025-08     20790385.0  4995275.0
2025-09     19965135.0  5110865.0
2025-10     19787265.0  5022185.0
2025-11     21831380.0  5543790.0
2025-12     22377675.0  5409095.0

In [90]:
channel_performance = sales_only.groupby("Channel").agg(
    Orders=("Order_ID", "count"),
    Sales=("Sales", "sum"),
    Profit=("Profit", "sum")
).sort_values("Sales", ascending=False)

channel_performance

             Orders       Sales      Profit
Channel
App            1937  97171515.0  24491425.0
Website        1975  94844990.0  23805790.0
Marketplace    1017  47186735.0  11717065.0

In [91]:
product_profitability = sales_only.groupby("Product").agg(
    Quantity=("Quantity", "sum"),
    Sales=("Sales", "sum"),
    Profit=("Profit", "sum")
).sort_values("Profit", ascending=False)

product_profitability

            Quantity        Sales      Profit
Product
Laptop          2129  105039000.0  28395000.0
Smartphone      2166   54580400.0  10177400.0
Tablet          2082   41169700.0   8898700.0
Monitor         2091   22534800.0   6643200.0
Webcam          2282    6580480.0   2244680.0
Headphones      2036    4578125.0   1829525.0
Keyboard        2300    3102375.0   1147375.0
Mouse           2238    1618360.0    678400.0

In [92]:
product_profitability["Profit_Margin"] = (
    product_profitability["Profit"] /
    product_profitability["Sales"]
)

product_profitability

            Quantity        Sales      Profit  Profit_Margin
Product
Laptop          2129  105039000.0  28395000.0       0.270328
Smartphone      2166   54580400.0  10177400.0       0.186466
Tablet          2082   41169700.0   8898700.0       0.216147
Monitor         2091   22534800.0   6643200.0       0.294797
Webcam          2282    6580480.0   2244680.0       0.341112
Headphones      2036    4578125.0   1829525.0       0.399623
Keyboard        2300    3102375.0   1147375.0       0.369838
Mouse           2238    1618360.0    678400.0       0.419190

In [93]:
region_performance = sales_only.groupby("Region").agg(
    Orders=("Order_ID", "count"),
    Sales=("Sales", "sum"),
    Profit=("Profit", "sum")
).sort_values("Profit", ascending=False)

region_performance

         Orders       Sales      Profit
Region
East       1384  68854910.0  17278560.0
South      1373  68312090.0  17072510.0
North      1438  66476030.0  16749990.0
West        733  35542930.0   8907340.0
Unknown       1     17280.0      5880.0

In [94]:
import numpy as np

# Start again from the untouched raw dataset
df_clean = df.copy()

# 1. Standardize text columns
df_clean["Category"] = (
    df_clean["Category"]
    .astype("string")
    .str.strip()
    .str.title()
)

df_clean["Region"] = (
    df_clean["Region"]
    .astype("string")
    .str.strip()
    .str.title()
)

df_clean["Channel"] = (
    df_clean["Channel"]
    .astype("string")
    .str.strip()
    .str.title()
)

# 2. Recover missing Customer_ID
df_clean["Customer_ID"] = df_clean["Customer_ID"].fillna("UNKNOWN")

# 3. Recover missing Category using the product's most common category
category_map = (
    df_clean.dropna(subset=["Category"])
    .groupby("Product")["Category"]
    .agg(lambda x: x.mode().iloc[0] if not x.mode().empty else "UNKNOWN")
)

df_clean["Category"] = (
    df_clean["Category"]
    .fillna(df_clean["Product"].map(category_map))
    .fillna("UNKNOWN")
)

# 4. Missing Region cannot be reliably inferred from Product
df_clean["Region"] = df_clean["Region"].fillna("UNKNOWN")

# 5. Correctly convert Discount
#    0.05 stays 0.05
#    "5%" becomes 0.05
discount_raw = df_clean["Discount"].astype("string").str.strip()
is_percent = discount_raw.str.endswith("%", na=False)

df_clean["Discount"] = pd.to_numeric(
    discount_raw.str.replace("%", "", regex=False),
    errors="coerce"
)

df_clean.loc[is_percent, "Discount"] = (
    df_clean.loc[is_percent, "Discount"] / 100
)

# 6. Recover missing Discount from Sales where possible
discount_from_sales = (
    1 - df_clean["Sales"] /
    (df_clean["Quantity"] * df_clean["Unit_Price"])
)

df_clean["Discount"] = df_clean["Discount"].fillna(discount_from_sales)

# 7. Convert dates
df_clean["Order_Date"] = pd.to_datetime(
    df_clean["Order_Date"],
    format="mixed",
    errors="coerce"
)

# 8. Recover missing Quantity
quantity_from_sales = (
    df_clean["Sales"] /
    (df_clean["Unit_Price"] * (1 - df_clean["Discount"]))
)

df_clean["Quantity"] = df_clean["Quantity"].fillna(quantity_from_sales)

# 9. Recover missing Sales
sales_from_formula = (
    df_clean["Quantity"] *
    df_clean["Unit_Price"] *
    (1 - df_clean["Discount"])
)

df_clean["Sales"] = df_clean["Sales"].fillna(sales_from_formula)

# 10. Remove exact duplicate records
df_clean = df_clean.drop_duplicates().copy()

# 11. Identify sales and returns
df_clean["Order_Type"] = np.where(
    df_clean["Quantity"] < 0,
    "Return",
    "Sale"
)

# 12. Calculate Profit and Profit Margin
df_clean["Profit"] = df_clean["Sales"] - df_clean["Cost"]

df_clean["Profit_Margin"] = np.where(
    df_clean["Order_Type"] == "Sale",
    df_clean["Profit"] / df_clean["Sales"],
    np.nan
)

# Recreate analysis subsets
sales_only = df_clean[df_clean["Order_Type"] == "Sale"].copy()
returns = df_clean[df_clean["Order_Type"] == "Return"].copy()

# Save corrected clean dataset
df_clean.to_csv(
    "../data/ecommerce_orders_clean.csv",
    index=False
)

print("CORRECTED CLEAN DATA")
print("--------------------")
print("Rows:", len(df_clean))
print("Columns:", len(df_clean.columns))
print("Missing values:", df_clean.isnull().sum().sum())
print("Duplicate rows:", df_clean.duplicated().sum())
print("Sales orders:", len(sales_only))
print("Return orders:", len(returns))

print("\nDiscount values:")
print(df_clean["Discount"].value_counts().sort_index())

CORRECTED CLEAN DATA
--------------------
Rows: 5000
Columns: 15
Missing values: 71
Duplicate rows: 0
Sales orders: 4929
Return orders: 71

Discount values:
Discount
0.0      993
0.05     982
0.1     1002
0.15    1040
0.2      983
Name: count, dtype: Int64

In [95]:
df_clean.isnull().sum()

Order_ID          0
Order_Date        0
Customer_ID       0
Product           0
Category          0
Region            0
Quantity          0
Unit_Price        0
Discount          0
Sales             0
Cost              0
Channel           0
Order_Type        0
Profit            0
Profit_Margin    71
dtype: int64

In [96]:
df_clean[df_clean["Profit_Margin"].isna()]["Order_Type"].value_counts()

Order_Type
Return    71
Name: count, dtype: int64

In [97]:
df_clean["Sales"].sum()

np.float64(237972050.0)

In [98]:
df_clean["Profit"].sum()

np.float64(59716980.0)

In [99]:
sales_only["Sales"].sum()

np.float64(239203240.0)

In [100]:
returns["Sales"].sum()

np.float64(-1231190.0)

In [101]:
sales_only["Profit"].sum() / sales_only["Sales"].sum()

np.float64(0.25089242102239084)

In [102]:
product_analysis = sales_only.groupby("Product").agg(
    Orders=("Order_ID", "count"),
    Quantity=("Quantity", "sum"),
    Sales=("Sales", "sum"),
    Profit=("Profit", "sum")
).sort_values("Sales", ascending=False)

product_analysis

            Orders  Quantity        Sales      Profit
Product
Laptop         604    2129.0  105039000.0  28395000.0
Smartphone     618    2166.0   54580400.0  10177400.0
Tablet         594    2082.0   41169700.0   8898700.0
Monitor        592    2091.0   22534800.0   6643200.0
Webcam         660    2282.0    6580480.0   2244680.0
Headphones     576    2036.0    4578125.0   1829525.0
Keyboard       652    2300.0    3102375.0   1147375.0
Mouse          633    2238.0    1618360.0    678400.0

In [103]:
product_analysis["Profit_Margin"] = (
    product_analysis["Profit"] /
    product_analysis["Sales"]
)

product_analysis

            Orders  Quantity        Sales      Profit  Profit_Margin
Product
Laptop         604    2129.0  105039000.0  28395000.0       0.270328
Smartphone     618    2166.0   54580400.0  10177400.0       0.186466
Tablet         594    2082.0   41169700.0   8898700.0       0.216147
Monitor        592    2091.0   22534800.0   6643200.0       0.294797
Webcam         660    2282.0    6580480.0   2244680.0       0.341112
Headphones     576    2036.0    4578125.0   1829525.0       0.399623
Keyboard       652    2300.0    3102375.0   1147375.0       0.369838
Mouse          633    2238.0    1618360.0    678400.0       0.419190

In [104]:
category_analysis = sales_only.groupby("Category").agg(
    Orders=("Order_ID", "count"),
    Quantity=("Quantity", "sum"),
    Sales=("Sales", "sum"),
    Profit=("Profit", "sum")
).sort_values("Sales", ascending=False)

category_analysis

             Orders  Quantity        Sales      Profit
Category
Electronics    2408    8468.0  223323900.0  54114300.0
Accessories    2521    8856.0   15879340.0   5899980.0

In [105]:
monthly_analysis = sales_only.groupby(
    sales_only["Order_Date"].dt.to_period("M")
).agg(
    Sales=("Sales", "sum"),
    Profit=("Profit", "sum")
)

monthly_analysis

                 Sales     Profit
Order_Date
2025-01     19945115.0  4985515.0
2025-02     17991185.0  4530945.0
2025-03     20305760.0  5181380.0
2025-04     19455330.0  5071250.0
2025-05     19724785.0  5101355.0
2025-06     15414915.0  3766425.0
2025-07     21614310.0  5296200.0
2025-08     20790385.0  4995275.0
2025-09     19965135.0  5110865.0
2025-10     19787265.0  5022185.0
2025-11     21831380.0  5543790.0
2025-12     22377675.0  5409095.0

In [106]:
monthly_analysis["Profit_Margin"] = (
    monthly_analysis["Profit"] /
    monthly_analysis["Sales"]
)

monthly_analysis

                 Sales     Profit  Profit_Margin
Order_Date
2025-01     19945115.0  4985515.0       0.249962
2025-02     17991185.0  4530945.0       0.251842
2025-03     20305760.0  5181380.0       0.255168
2025-04     19455330.0  5071250.0       0.260661
2025-05     19724785.0  5101355.0       0.258627
2025-06     15414915.0  3766425.0       0.244336
2025-07     21614310.0  5296200.0       0.245032
2025-08     20790385.0  4995275.0       0.240269
2025-09     19965135.0  5110865.0       0.255990
2025-10     19787265.0  5022185.0       0.253809
2025-11     21831380.0  5543790.0       0.253937
2025-12     22377675.0  5409095.0       0.241718

In [107]:
channel_analysis = sales_only.groupby("Channel").agg(
    Orders=("Order_ID", "count"),
    Sales=("Sales", "sum"),
    Profit=("Profit", "sum")
).sort_values("Sales", ascending=False)

channel_analysis

             Orders       Sales      Profit
Channel
App            1937  97171515.0  24491425.0
Website        1975  94844990.0  23805790.0
Marketplace    1017  47186735.0  11717065.0

In [108]:
region_analysis = sales_only.groupby("Region").agg(
    Orders=("Order_ID", "count"),
    Sales=("Sales", "sum"),
    Profit=("Profit", "sum")
).sort_values("Sales", ascending=False)

region_analysis

         Orders       Sales      Profit
Region
East       1384  68854910.0  17278560.0
South      1373  68312090.0  17072510.0
North      1438  66476030.0  16749990.0
West        733  35542930.0   8907340.0
UNKNOWN       1     17280.0      5880.0

## Business Findings

### Overall Performance
- Net sales and net profit were calculated after cleaning the transaction data.
- Returns were identified separately from normal sales.
- Overall profit margin was also calculated for sale transactions.

### Product Performance
- Laptop generated the highest sales and profit contribution.
- Mouse had a higher profit margin despite much lower revenue.
- This shows that sales value and profitability should be analyzed together.

### Category Performance
- Electronics generated substantially more revenue and profit than Accessories.
- Accessories had high unit volume but lower revenue because of lower-priced products.

### Monthly Performance
- Monthly sales and profit were compared to identify stronger and weaker periods.
- The monthly analysis helps identify changes in business performance over time.

### Channel Performance
- App and Website generated similar sales and profit.
- Marketplace contributed less sales and profit than the other two channels.

### Return Analysis
- 71 orders were identified as returns.
- Returns created a negative impact on sales and profit.
- Return activity should therefore be monitored separately from normal sales.

In [109]:
import sqlite3

conn = sqlite3.connect("../data/ecommerce_sales.db")

df_clean.to_sql(
    "orders",
    conn,
    if_exists="replace",
    index=False
)

5000

In [110]:
query = """
SELECT COUNT(*) AS total_orders
FROM orders;
"""

pd.read_sql_query(query, conn)

   total_orders
0          5000

In [112]:
query = """
SELECT
    SUM(Sales) AS Net_Sales,
    SUM(Profit) AS Net_Profit,
    ROUND(
        SUM(Profit) * 100.0 / NULLIF(SUM(Sales), 0),
        2
    ) AS Profit_Margin_Percent
FROM orders;
"""

pd.read_sql_query(query, conn)

     Net_Sales  Net_Profit  Profit_Margin_Percent
0  237972050.0  59716980.0                  25.09

In [113]:
query = """
SELECT
    Product,
    SUM(Quantity) AS Total_Quantity,
    SUM(Sales) AS Total_Sales,
    SUM(Profit) AS Total_Profit,
    ROUND(
        SUM(Profit) * 100.0 / NULLIF(SUM(Sales), 0),
        2
    ) AS Profit_Margin_Percent
FROM orders
WHERE Order_Type = 'Sale'
GROUP BY Product
ORDER BY Total_Sales DESC;
"""

pd.read_sql_query(query, conn)

,Product,Total_Quantity,Total_Sales,Total_Profit,Profit_Margin_Percent
0,Laptop,2129.0,105039000.0,28395000.0,27.03
1,Smartphone,2166.0,54580400.0,10177400.0,18.65
2,Tablet,2082.0,41169700.0,8898700.0,21.61
3,Monitor,2091.0,22534800.0,6643200.0,29.48
4,Webcam,2282.0,6580480.0,2244680.0,34.11
5,Headphones,2036.0,4578125.0,1829525.0,39.96
6,Keyboard,2300.0,3102375.0,1147375.0,36.98
7,Mouse,2238.0,1618360.0,678400.0,41.92

In [114]:
query = """
SELECT
    Category,
    COUNT(*) AS Total_Orders,
    SUM(Quantity) AS Total_Quantity,
    SUM(Sales) AS Total_Sales,
    SUM(Profit) AS Total_Profit,
    ROUND(
        SUM(Profit) * 100.0 / NULLIF(SUM(Sales), 0),
        2
    ) AS Profit_Margin_Percent
FROM orders
WHERE Order_Type = 'Sale'
GROUP BY Category
ORDER BY Total_Sales DESC;
"""

pd.read_sql_query(query, conn)

,Category,Total_Orders,Total_Quantity,Total_Sales,Total_Profit,Profit_Margin_Percent
0,Electronics,2408,8468.0,223323900.0,54114300.0,24.23
1,Accessories,2521,8856.0,15879340.0,5899980.0,37.16

In [115]:
query = """
SELECT
    strftime('%Y-%m', Order_Date) AS Month,
    SUM(Sales) AS Total_Sales,
    SUM(Profit) AS Total_Profit,
    ROUND(
        SUM(Profit) * 100.0 / NULLIF(SUM(Sales), 0),
        2
    ) AS Profit_Margin_Percent
FROM orders
WHERE Order_Type = 'Sale'
GROUP BY Month
ORDER BY Month;
"""

pd.read_sql_query(query, conn)

      Month  Total_Sales  Total_Profit  Profit_Margin_Percent
0   2025-01   19945115.0     4985515.0                  25.00
1   2025-02   17991185.0     4530945.0                  25.18
2   2025-03   20305760.0     5181380.0                  25.52
3   2025-04   19455330.0     5071250.0                  26.07
4   2025-05   19724785.0     5101355.0                  25.86
5   2025-06   15414915.0     3766425.0                  24.43
6   2025-07   21614310.0     5296200.0                  24.50
7   2025-08   20790385.0     4995275.0                  24.03
8   2025-09   19965135.0     5110865.0                  25.60
9   2025-10   19787265.0     5022185.0                  25.38
10  2025-11   21831380.0     5543790.0                  25.39
11  2025-12   22377675.0     5409095.0                  24.17

In [116]:
query = """
SELECT
    Discount,
    COUNT(*) AS Total_Orders,
    SUM(Sales) AS Total_Sales,
    SUM(Profit) AS Total_Profit,
    ROUND(
        SUM(Profit) * 100.0 / NULLIF(SUM(Sales), 0),
        2
    ) AS Profit_Margin_Percent
FROM orders
WHERE Order_Type = 'Sale'
GROUP BY Discount
ORDER BY Discount;
"""

pd.read_sql_query(query, conn)

   Discount  Total_Orders  Total_Sales  Total_Profit  Profit_Margin_Percent
0      0.00           978   51146200.0    16803300.0                  32.85
1      0.05           968   49155280.0    14288860.0                  29.07
2      0.10           984   49544190.0    12405000.0                  25.04
3      0.15          1028   45734930.0     9439250.0                  20.64
4      0.20           971   43622640.0     7077870.0                  16.23

In [117]:
query = """
SELECT
    COUNT(*) AS Return_Orders,
    SUM(Quantity) AS Returned_Units,
    SUM(Sales) AS Return_Sales_Impact,
    SUM(Profit) AS Return_Profit_Impact
FROM orders
WHERE Order_Type = 'Return';
"""

pd.read_sql_query(query, conn)

   Return_Orders  Returned_Units  Return_Sales_Impact  Return_Profit_Impact
0             71          -103.0           -1231190.0             -297300.0

In [118]:
query = """
SELECT
    Product,
    COUNT(*) AS Return_Orders,
    ABS(SUM(Quantity)) AS Returned_Units,
    ABS(SUM(Sales)) AS Return_Sales_Impact,
    ABS(SUM(Profit)) AS Return_Profit_Impact
FROM orders
WHERE Order_Type = 'Return'
GROUP BY Product
ORDER BY Returned_Units DESC;
"""

pd.read_sql_query(query, conn)

,Product,Return_Orders,Returned_Units,Return_Sales_Impact,Return_Profit_Impact
0,Smartphone,14,18.0,457800.0,88800.0
1,Webcam,10,17.0,48320.0,16020.0
2,Mouse,13,17.0,12120.0,4980.0
3,Tablet,9,13.0,248600.0,47100.0
4,Headphones,9,13.0,28750.0,11200.0
5,Monitor,7,11.0,127200.0,43600.0
6,Keyboard,5,8.0,11400.0,4600.0
7,Laptop,4,6.0,297000.0,81000.0

In [119]:
query = """
WITH product_orders AS (
    SELECT
        Product,
        COUNT(*) AS Total_Orders,
        SUM(
            CASE
                WHEN Order_Type = 'Return' THEN 1
                ELSE 0
            END
        ) AS Return_Orders
    FROM orders
    GROUP BY Product
)

SELECT
    Product,
    Total_Orders,
    Return_Orders,
    ROUND(
        Return_Orders * 100.0 / NULLIF(Total_Orders, 0),
        2
    ) AS Return_Rate_Percent
FROM product_orders
ORDER BY Return_Rate_Percent DESC;
"""

pd.read_sql_query(query, conn)

      Product  Total_Orders  Return_Orders  Return_Rate_Percent
0  Smartphone           632             14                 2.22
1       Mouse           646             13                 2.01
2  Headphones           585              9                 1.54
3      Tablet           603              9                 1.49
4      Webcam           670             10                 1.49
5     Monitor           599              7                 1.17
6    Keyboard           657              5                 0.76
7      Laptop           608              4                 0.66

In [120]:
query = """
SELECT
    Customer_ID,
    COUNT(*) AS Orders,
    SUM(Sales) AS Total_Sales,
    SUM(Profit) AS Total_Profit
FROM orders
WHERE Order_Type = 'Sale'
GROUP BY Customer_ID
ORDER BY Total_Sales DESC
LIMIT 10;
"""

pd.read_sql_query(query, conn)

  Customer_ID  Orders  Total_Sales  Total_Profit
0    CUST1289      14    1554055.0      465565.0
1    CUST1163      20    1511660.0      414850.0
2    CUST1347      18    1494030.0      393830.0
3    CUST1214      16    1469280.0      332240.0
4    CUST1387      17    1464695.0      359305.0
5    CUST1359      17    1259225.0      276635.0
6    CUST1223      11    1212785.0      344875.0
7    CUST1350      18    1212225.0      259075.0
8    CUST1404      12    1170130.0      272980.0
9    CUST1217      13    1160900.0      334750.0

In [4]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("../data/ecommerce_sales.db")

pd.read_sql_query("SELECT COUNT(*) AS total_orders FROM orders;", conn)

   total_orders
0          5000

In [5]:
query = """
SELECT
    Customer_ID,
    COUNT(*) AS Orders,
    SUM(Sales) AS Total_Sales,
    SUM(Profit) AS Total_Profit
FROM orders
WHERE Order_Type = 'Sale'
GROUP BY Customer_ID
ORDER BY Total_Sales DESC
LIMIT 10;
"""

pd.read_sql_query(query, conn)

  Customer_ID  Orders  Total_Sales  Total_Profit
0    CUST1289      14    1554055.0      465565.0
1    CUST1163      20    1511660.0      414850.0
2    CUST1347      18    1494030.0      393830.0
3    CUST1214      16    1469280.0      332240.0
4    CUST1387      17    1464695.0      359305.0
5    CUST1359      17    1259225.0      276635.0
6    CUST1223      11    1212785.0      344875.0
7    CUST1350      18    1212225.0      259075.0
8    CUST1404      12    1170130.0      272980.0
9    CUST1217      13    1160900.0      334750.0

In [6]:
query = """
SELECT
    Customer_ID,
    COUNT(*) AS Orders,
    SUM(Sales) AS Total_Sales,
    SUM(Profit) AS Total_Profit
FROM orders
WHERE Order_Type = 'Sale'
GROUP BY Customer_ID
ORDER BY Total_Profit DESC
LIMIT 10;
"""

pd.read_sql_query(query, conn)

  Customer_ID  Orders  Total_Sales  Total_Profit
0    CUST1289      14    1554055.0      465565.0
1    CUST1163      20    1511660.0      414850.0
2    CUST1347      18    1494030.0      393830.0
3    CUST1387      17    1464695.0      359305.0
4    CUST1223      11    1212785.0      344875.0
5    CUST1005      13    1098510.0      337510.0
6    CUST1217      13    1160900.0      334750.0
7    CUST1214      16    1469280.0      332240.0
8    CUST1411      16    1118635.0      298095.0
9    CUST1172      11    1095300.0      292640.0

In [7]:
query = """
SELECT
    Discount,
    COUNT(*) AS Orders,
    ROUND(SUM(Sales), 2) AS Total_Sales,
    ROUND(SUM(Profit), 2) AS Total_Profit,
    ROUND(
        SUM(Profit) * 100.0 / NULLIF(SUM(Sales), 0),
        2
    ) AS Profit_Margin_Percent
FROM orders
WHERE Order_Type = 'Sale'
GROUP BY Discount
ORDER BY Discount;
"""

pd.read_sql_query(query, conn)

   Discount  Orders  Total_Sales  Total_Profit  Profit_Margin_Percent
0      0.00     978   51146200.0    16803300.0                  32.85
1      0.05     968   49155280.0    14288860.0                  29.07
2      0.10     984   49544190.0    12405000.0                  25.04
3      0.15    1028   45734930.0     9439250.0                  20.64
4      0.20     971   43622640.0     7077870.0                  16.23

In [8]:
query = """
SELECT
    Channel,
    COUNT(*) AS Orders,
    SUM(Quantity) AS Total_Quantity,
    SUM(Sales) AS Total_Sales,
    SUM(Profit) AS Total_Profit,
    ROUND(
        SUM(Profit) * 100.0 / NULLIF(SUM(Sales), 0),
        2
    ) AS Profit_Margin_Percent
FROM orders
WHERE Order_Type = 'Sale'
GROUP BY Channel
ORDER BY Total_Sales DESC;
"""

pd.read_sql_query(query, conn)

,Channel,Orders,Total_Quantity,Total_Sales,Total_Profit,Profit_Margin_Percent
0,App,1937,6854.0,97171515.0,24491425.0,25.20
1,Website,1975,6803.0,94844990.0,23805790.0,25.10
2,Marketplace,1017,3667.0,47186735.0,11717065.0,24.83

In [9]:
query = """
SELECT
    Region,
    COUNT(*) AS Orders,
    SUM(Quantity) AS Total_Quantity,
    SUM(Sales) AS Total_Sales,
    SUM(Profit) AS Total_Profit,
    ROUND(
        SUM(Profit) * 100.0 / NULLIF(SUM(Sales), 0),
        2
    ) AS Profit_Margin_Percent
FROM orders
WHERE Order_Type = 'Sale'
GROUP BY Region
ORDER BY Total_Sales DESC;
"""

pd.read_sql_query(query, conn)

,Region,Orders,Total_Quantity,Total_Sales,Total_Profit,Profit_Margin_Percent
0,East,1384,4842.0,68854910.0,17278560.0,25.09
1,South,1373,4861.0,68312090.0,17072510.0,24.99
2,North,1438,5051.0,66476030.0,16749990.0,25.20
3,West,733,2564.0,35542930.0,8907340.0,25.06
4,UNKNOWN,1,6.0,17280.0,5880.0,34.03

In [10]:
query = """
SELECT
    COUNT(*) AS Repeat_Customers
FROM (
    SELECT
        Customer_ID
    FROM orders
    WHERE Order_Type = 'Sale'
      AND Customer_ID <> 'UNKNOWN'
    GROUP BY Customer_ID
    HAVING COUNT(*) > 1
);
"""

pd.read_sql_query(query, conn)

   Repeat_Customers
0               450

In [11]:
query = """
WITH product_profit AS (
    SELECT
        Category,
        Product,
        SUM(Sales) AS Total_Sales,
        SUM(Profit) AS Total_Profit
    FROM orders
    WHERE Order_Type = 'Sale'
    GROUP BY Category, Product
)

SELECT
    Category,
    Product,
    ROUND(Total_Sales, 2) AS Total_Sales,
    ROUND(Total_Profit, 2) AS Total_Profit,
    RANK() OVER (
        PARTITION BY Category
        ORDER BY Total_Profit DESC
    ) AS Profit_Rank
FROM product_profit
ORDER BY Category, Profit_Rank;
"""

pd.read_sql_query(query, conn)

      Category     Product  Total_Sales  Total_Profit  Profit_Rank
0  Accessories      Webcam    6580480.0     2244680.0            1
1  Accessories  Headphones    4578125.0     1829525.0            2
2  Accessories    Keyboard    3102375.0     1147375.0            3
3  Accessories       Mouse    1618360.0      678400.0            4
4  Electronics      Laptop  105039000.0    28395000.0            1
5  Electronics  Smartphone   54580400.0    10177400.0            2
6  Electronics      Tablet   41169700.0     8898700.0            3
7  Electronics     Monitor   22534800.0     6643200.0            4